### ISSUE TITLE
KPIMON DockerFile

### ISSUE THREAD

**Issue by mrkouchaki** [openaicellular/oaic#4]
I'm using this "git clone https://gitlab.flux.utah.edu/powderrenewpublic/ric-scp-kpimon.git" for getting DockerFile, but faced with problems, docker could not connect to some repositories.

**Comment by pratheeksu** [comment]
This error is basically because of an outdated version of Go (Go 1.12) installed in the base image [nexus3.o-ran-sc.org](http://nexus3.o-ran-sc.org/):10002/o-ran-sc/bldr-ubuntu18-c-go:1.9.0. This version fails some of the certificate checks and has broken links to revisions of Github repositories (Similar to this [gopkg.in/yaml.v2@v2.2.4](http://gopkg.in/yaml.v2@v2.2.4): unknown revision v2.2.4). That's why I guess it's stuck in the finding state and not downloading the dependencies. The fix is to use Ubuntu 20.04 image hosted by O-RAN-SC, which comes with GO 1.16. You can also build the image on your own using the Dockerfile hosted on https://gerrit.o-ran-sc.org/r/gitweb?p=it/dev.git;a=blob;f=bldr-imgs/bldr-ubuntu20-c-go/Dockerfile;h=8ddeb231c1631c4d25812c3c9527a38c29f0ae16;hb=HEAD. Here, you can change the version of Go to 1.17 too and build the base bldr-ubuntu20-c-go:1.0.0 image.



Change the 1st line of the Docker file to 

FROM [nexus3.o-ran-sc.org](http://nexus3.o-ran-sc.org/):10002/o-ran-sc/bldr-ubuntu20-c-go:1.0.0 as kpimonbuild



Since we will be using Go 1.16 after the above change and Go 1.16 builds packages in module-aware mode by default, we need to set the environment variable GO111MODULE to off. So, just before

RUN go build ./cmd/kpimon.go && pwd && ls -lat add the line RUN go env -w GO111MODULE=off. So it basically looks like this,



RUN mkdir pkg

RUN go env -w GO111MODULE=off
RUN go build ./cmd/kpimon.go && pwd && ls -lat

FROM ubuntu:20.04       # The original Dockerfile uses an ubuntu 18.04 image. Change to 20.04



If the GO111MODULE=off is not set, an error occurs, asking for the go.mod file. Also, don't modify the line  GO111MODULE=on go mod vendor -v. If you set the GO111MODULE=off here, then the package dependencies will not be resolved cleanly since the compiler will not identify gerrit.o-ran-sc.org/r/ric-plt/xapp-frame/pkg/xapp as a valid package.



More information regarding GO111MODULE and go.mod can be found here: https://maelvls.dev/go111module-everywhere/.
